const menu_data = [
  // {
  //   id: 1,
  //   mega_menu: false,
  //   title: "Home",
  //   link: "/",
  //   active: "active",
  // },
  {
    id: 1,
    mega_menu: false,
    has_dropdown: false,
    title: "AI Chat",
    link: "/ai-chat",
    active: "",
  },

  {
    id: 2,
    mega_menu: false,
    has_dropdown: true,
    title: "AI Tools",
    link: "/ai-tools",
    active: "",
    sub_menus: [
      { link: "/ai-tools/assured-seo", title: "Assured SEO" },
      { link: "/ai-tools/humanize-content", title: "Humanize Content" },
      { link: "/ai-tools/ppt-generator", title: "PPT Generator" },
      { link: "/ai-tools/summarizer", title: "Summarizer" },
      { link: "/ai-tools/image-to-text", title: "Image To Text" },
      { link: "/ai-tools/scan-to-native", title: "Scan To Native PDF" },
    ],
  },

  {
    id: 3,
    mega_menu: false,
    has_dropdown: false,
    title: "AI Assistant",
    link: "/ai-assistant",
    active: "",
    // sub_menus: [
    //   { link: "/ai-assistant/blog-tools", title: "Blog Tools" },
    //   { link: "/ai-assistant/social-media-tools", title: "Social Media Tools" },
    //   { link: "/ai-assistant/youtube-tools", title: "Youtube Tools" },
    //   { link: "/ai-assistant/seo-tools", title: "SEO Tools" },
    //   { link: "/ai-assistant/advertising-tools", title: "Adverising Tools" },
    //   { link: "/ai-assistant/writing-assistant-tools", title: "Writing Assistant Tools" },
    //   { link: "/ai-assistant/ai-assistant", title: "Explore All" },
    // { link: "/website-content-tools", title: "Website Content Tools" },
    // { link: "/email-tools", title: "Email Tools" },
    // { link: "/aplication-tools", title: "Aplication Tools" },
    // { link: "/e-commerce-tools", title: "Ecpmmerce Tools" },
    // { link: "/idea-generation-tools", title: "Idea Generation Tools" },
    // { link: "/image-prompts-tools", title: "Image Prompts Tools" },
    // { link: "/re-purpose-tools", title: "Re Purpose Tools" },
    // { link: "/hr-tools", title: "Hr Tools" },
    // { link: "/music-tools", title: "Music Tools" },
    // { link: "/web-story-tools", title: "Web Story Tools" },
    // ],
  },

  {
    id: 4,
    mega_menu: false,
    has_dropdown: false,
    title: "About",
    link: "/about",
    active: "",
    // sub_menus: [
    //   { link: "/about", title: "About" },
    //   { link: "/service", title: "Service" },
    //   { link: "/service-details", title: "Service Details" },
    //   { link: "/team", title: "Team" },
    //   { link: "/team-details", title: "Team Details" },
    //   { link: "/career", title: "Career" },
    //   { link: "/career-details", title: "Career Details" },
    //   { link: "/integrations", title: "Integrations" },
    //   { link: "/price", title: "Price" },
    //   { link: "/register", title: "Register" },
    //   { link: "/sign-in", title: "Signin" },
    //   { link: "/404", title: "404" },
    // ],
  },

  {
    id: 5,
    mega_menu: false,
    has_dropdown: false,
    title: "Blog",
    link: "/blog",
    active: "",
    // sub_menus: [
    //   { link: "/blog-details", title: "Blog Details" },
    // ],
  },

  {
    id: 6,
    mega_menu: false,
    has_dropdown: false,
    title: "Contact",
    link: "/contact",
    active: "",
  },
];
export default menu_data;
